### ISSUE TITLE
[Fatal Error] :522:13: The string "--" is not permitted within comments.

### ISSUE THREAD

**Issue by punisher018** [inotia00/rvx-builder#120]
**Describe the bug**
It gives an error in the patching section at the last stage

**To Reproduce**

**Screenshots**

**revanced-builder Version:** [e.g. v1.2.10]
rvx-builder v3.10.1

**Desktop (please complete the following information):**

- OS: [e.g. Windows]
- Windows 10

**Additional context**
[Error Log.txt](https://github.com/inotia00/rvx-builder/files/13064471/Error.Log.txt)

**Comment by Shaarigan** [comment]
I just tested 3.10.1 on Windows 10 and it worked for me. Try close RVX-Builder and clear your RVX-Builder directory by removing everything except

- options.json
- rvx-builder-win.exe
- settings.json
- revanced/revanced.keystore

Then restart RVX-Builder, it will download latest files. If that doesn't work try to patch an older supported version of whatever App you wanted to patch. If that doesn't work either, try to clear the entire directory and download latest RVX-Builder again

**Comment by punisher018** [comment]
I can patch reddit with the existing builder without any problem, but no matter which version I patch on youtube, it gives the error I wrote. Before opening the topic, I had already tried deleting the existing folder completely and downloading all the files again and nothing changed. The same builder version (3.10.1) was patching before (if I remember correctly, the patch files supported were youtube 18.36 and 18.37) without any problem. It broke after updating revanced integrations and revanced patches files.

**Comment by Shaarigan** [comment]
Like I wrote, I was able to patch 18.37.44 yesterday without problems. Let me have a look what's the latest supported YT and I'll try with that one and see if it works

**Comment by Shaarigan** [comment]
So for me it worked using YT 18.40.34, CLI 4.0.3 and patches v2.195.1. I however had to "upload" my own APK file because APKMirror API is blocked on my maschine and I had no files in my directory except for options, settings and keystore

[log.txt](https://github.com/inotia00/rvx-builder/files/13187315/log.txt)

This might be an issue on your device then. Could you try a different file path for builder, run with admin permission and to add upload your own apk from APKMirror instead of using the auto select from builder?

And if that doesn't work try switching to the official sources
https://user-images.githubusercontent.com/20586878/265737079-39750827-5ec1-4a08-8c93-2d135ec14ae4.png

I also tested patching latest YT supported by official sources with builder and it also worked well for me

**Comment by punisher018** [comment]
My problem has been solved. But I don't understand how it was solved. I even tried before by creating another folder on another disk and it didn't work. (I also tried as admin) But I didn't delete the folder I used before. 
Now I deleted this folder and when I tried again from the beginning, it worked. (So I think this must be the reason, because I didn't try anything else)
Thanks for your effort
