### ISSUE TITLE
Support Android TV or Android Box compatible YouTube application

### ISSUE THREAD

**Issue by abdullah-erturk** [inotia00/rvx-builder#127]
Please also add support for Android TV or Android Box compatible YouTube application.

**Comment by Tumpo** [comment]
See [SmartTube](https://github.com/yuliskov/SmartTube).

**Comment by Shaarigan** [comment]
YouTube for Smart TVs isn't a real App rather than a chromium Browser that just interacts with the original YouTube Web Page as far as I know. So this means you can't patch it and using [SmartTubeNext](https://github.com/yuliskov/SmartTube) is your best option to run right now.

Honestly I don't like it either but its the best alternative or you use stock YouTube App and attach a mouse to whatever device you want it to run. Or have a TV Box that already comes with a remote that has some kind of mouse built-in
