### ISSUE TITLE
Question: Differences between the upstream revanced-builder?

### ISSUE THREAD

**Issue by shrihanDev** [inotia00/rvx-builder#19]
Title.

**Comment by inotia00** [comment]
what do you mean?

**Comment by shrihanDev** [comment]
I mean, it's been so popular and all but how is it different from reisxd/revanced-builder? I mean I didn't see any commits other than the ones in the upstream. Just curious :)

**Comment by inotia00** [comment]
Unsurprisingly, it is entirely identical to revanced-builder
It's just that I made a little modification so that I can download the tool from the repo I provide.

The reason I changed the name of the fork repo from revanced-builder to rvx-builder is simply because I wanted to use revanced-builder and rvx-builder at the same time.

**Comment by shrihanDev** [comment]
Oh, thanks!
