### ISSUE TITLE
Mount error

### ISSUE THREAD

**Issue by RENOMIZER** [inotia00/rvx-builder#23]
In the finishing steps when script is trying to mount an app this error occurs. And it doesn't even matter what patches you use.

![Screenshot_20221129-004159_Firefox](https://user-images.githubusercontent.com/94466218/204387645-0f0a5604-fa7a-4a5b-8c5d-afb39980000b.png)

Was using the latest version of builder, 3.5.0

- OS: Android 
- Version: 11

UPD: Turns out if you delete an unpached app and then install a patched one it will work just fine, but still this doesn't solve the problem of it not being able to do all the thing automatically

**Comment by RENOMIZER** [comment]
UPD: Turns out if you delete an unpached app and then install a patched one it will work just fine, but still this doesn't solve the problem of it not being able to do all the thing automatically

**Comment by inotia00** [comment]
This error occurs because it is already mounted on your device.

Perhaps, you have previously installed ReVanced in the ROOT environment through another method, or the Magisk module is installed, or there are still traces of the previous installation.

Before running rvx-builder, follow the guide

https://github.com/inotia00/revanced-documentation/wiki/Method-2.-Using-RVX-Builder-(Windows---MacOS---Linux---Android)#common
