### ISSUE TITLE
Win 7 rvx-builder v3.4.15

### ISSUE THREAD

**Issue by deleteBlack666** [inotia00/rvx-builder#4]
rvx-builder v3.4.15

- OS: Windows
- Version: Win 7 
I i run rvx-builder and it crashes just a window appears and disappears

**Comment by inotia00** [comment]
sorry for the late reply
Check the java environment variable settings.

> rvx-builder v3.4.15
> 
> * OS: Windows
> * Version: Win 7
>   I i run rvx-builder and it crashes just a window appears and disappears

sorry for the late reply
Check the java environment variable settings.

**Comment by inotia00** [comment]
> > java
> > where can i download it i dont have it

https://cdn.azul.com/zulu/bin/zulu17.36.17-ca-jdk17.0.4.1-win_x64.msi

But it seems to me that you have already downloaded the correct Java

Reinstall the previously installed Java, or check whether JAVA_HOME is set properly.

Refer to [this](https://confluence.atlassian.com/conf59/setting-the-java_home-variable-in-windows-792499849.html) and set JAVA_HOME

Instead of `C:\Program Files\Java\jdk1.8.0_65`, enter the path where Zulu 17 is installed
