### ISSUE TITLE
Device or resource busy

### ISSUE THREAD

**Issue by jackson177** [inotia00/rvx-builder#42]
**Describe the bug**
An error occured:Error: Command failed: su -c 'base_path="/data/adb/revanced/com.google.android.youtube.apk" && mv -f "/data/adb/revanced/ReVanced-YouTube-v18.01.36-cli_v2.20.1-patches_v2.153.4.apk" "$base_path" && chmod 644 "$base_path" && chown system:system "$base_path" && chcon u:object_r:apk_data_file:s0 "$base_path"'mv: bad '/data/adb/revanced/ReVanced-YouTube-v18.01.36-cli_v2.20.1-patches_v2.153.4.apk': Device or resource busyat ChildProcess.exithandler (node:child_process:419:12)at ChildProcess.emit (node:events:513:28)at maybeClose (node:internal/child_process:1091:16)at ChildProcess._handle.onexit (node:internal/child_process:302:5)

**To Reproduce**

1. Just building 
**Screenshots**

**revanced-builder Version:** [e.g. latest]

**Desktop (please complete the following information):**

- OS: android 
- Version: 13

**Additional context**

**Comment by mainsm** [comment]
I received almost the same error.  I upgraded to Android 13 with Youtube still patched and after rebooting its name changed to APPLICATION_LIGHT (if I recall correctly) and it wouldn't open.  I then removed all updates and tried to patch YouTube again with rvx-builder through Termux.  I updated rvx-builder first and updated YouTube to the preferred version, 18.0.1.36.  This is what my error message said:

[builder] An error occured: Error: Command failed: su -c 'base_path="/data/adb/revanced/com.google.andro && mv -f "/data/adb/revanced/ReVanced-YouTube- cli_v2.20.1-patches_v2.153.6.apk" "$base_path" 66 chmod 644 "$base_path" && chown system:system "$base_path" && chcon u:object_r:apk_data_file: s0 "$base_path" mv: bad /data/adb/revanced/ReVanced-YouTube- cli_v2.20.1-patches_v2.153.6.apk': Device or resource busy

at ChildProcess.exithandler (node:child_process:402:12) at ChildProcess.emit (node:events:513:28) at maybeClose (node: internal/child_process:1100:16) at Process.ChildProcess._handle.onexit (node: internal/child_process:304:5) Please report this bug here: https://github.com/inotia00/rvx- builder/issues.


I then tried building it in Windows 10 but got a different error: 

[builder] An error occured:
Error: EBUSY: resource busy or locked, unlink '\\?\M:\rvx-builder\revanced-cache\1.apk'
at unlinkSync (node:fs:1780:3)
at _unlinkSync (node:internal/fs/rimraf:214:14)
at rimrafSync (node:internal/fs/rimraf:195:7)
at node:internal/fs/rimraf:253:9at Array.forEach ()
at _rmdirSync (node:fs:1274:10)
at afterbuild (C:\snapshot\rvx-builder2\wsEvents\patchApp.js:28:3)
at Socket. (C:\snapshot\rvx-builder2\wsEvents\patchApp.js:186:53)

**Comment by inotia00** [comment]
This issue occurs if you have ever installed ReVanced / ReVanced Extended via ReVanced Manager or Magisk Module

Please refer to the documentations
https://github.com/inotia00/revanced-documentation/wiki/Method-2.-Using-RVX-Builder-(Windows---MacOS---Linux---Android)#0-if-you-are-preparing-to-install-in-root-environment-follow-the-method-below
