### ISSUE TITLE
[Docker] Error: spawn ps ENOENT 

### ISSUE THREAD

**Issue by dausruddin** [inotia00/rvx-builder#93]
**Describe the bug**
There are a few issues already, but none of them related to docker. I am running this using docker with [V.3.9.2](https://github.com/inotia00/rvx-builder/releases/tag/v3.9.2), and followed [docker-compose guide](https://github.com/inotia00/rvx-builder/blob/main/README.md#build-using-docker-compose).

**To Reproduce**

1. Download [v3.9.2 source](https://github.com/inotia00/rvx-builder/archive/refs/tags/v3.9.2.zip) and unzip it.
2. `docker-compose build --pull --no-cache`
3. `docker-compose up -d`
4. Open `http://localhost:8000` and start patching.

**Screenshots**
![Screenshot_20230511-162913_Kiwi Browser](https://github.com/inotia00/rvx-builder/assets/5763466/0a9bb343-1cc5-4474-80cc-c80ace3d1b79)

**revanced-builder Version:**
v3.9.2

**Desktop (please complete the following information):**

- OS: ArchLinux
- Version: -

**Additional context**
N/A

**Comment by inotia00** [comment]
Similar to this issue https://github.com/inotia00/rvx-builder/issues/91

I've never had my default branch set to `revanced-extended` after forking until now.
Because of this, until now, downloading the source from releases would have downloaded the source from the `main` branch.

Now that I have changed the default branch to `revanced-extended`, the source will be downloaded from the `revanced-extended` branch from next release.

Temporarily, download the source from the `revanced-extended` branch of the manual.

Download [v3.9.2 source (revanced-extended)](https://github.com/inotia00/rvx-builder/archive/refs/heads/revanced-extended.zip)
